/****************************************************************************
** Form interface generated from reading ui file '.\Forms\amonsoft.ui'
**
** Created: ven. 6. avr. 16:32:19 2007
**      by: The User Interface Compiler ($Id: amonsoft.h,v 1.30 2007/04/06 15:34:44 pascal Exp $)
**
** WARNING! All changes made in this file will be lost!
****************************************************************************/

#ifndef DLGMAIN_H
#define DLGMAIN_H

#include <qvariant.h>
#include <qmainwindow.h>

class QVBoxLayout;
class QHBoxLayout;
class QGridLayout;
class QSpacerItem;
class QAction;
class QActionGroup;
class QToolBar;
class QPopupMenu;
class QPushButton;
class QWidgetStack;
class QWidget;
class QLabel;
class QFrame;
class QComboBox;
class QLineEdit;
class QDateEdit;
class QTabWidget;
class QCheckBox;
class QTextEdit;
class QListView;
class QListViewItem;
class QSlider;

class dlgAmonSoft : public QMainWindow
{
    Q_OBJECT

public:
    dlgAmonSoft( QWidget* parent = 0, const char* name = 0, WFlags fl = WType_TopLevel );
    ~dlgAmonSoft();

    QPushButton* pushButtonPersonneLister;
    QPushButton* pushButtonPersonneAjouter;
    QPushButton* pushButtonEntrepriseLister;
    QPushButton* pushButton44;
    QPushButton* pushButtonCharger;
    QPushButton* pushButtonSupprimer;
    QWidgetStack* widgetStackMain;
    QWidget* WStackPage;
    QPushButton* pushButtonEtatCivil;
    QPushButton* pushButtonFamille;
    QPushButton* pushButtonCarriere;
    QPushButton* pushButtonPrevoyance;
    QPushButton* pushButtonEpargne;
    QPushButton* pushButtonPatrimoine;
    QPushButton* pushButtonBesoins;
    QWidgetStack* widgetStackAjouter;
    QWidget* WStackPage_2;
    QLabel* labelEtatCivil;
    QFrame* frameBeneficiaire;
    QLabel* textLabelEtatCivilRue;
    QLabel* textLabelEtatCivilAdresseComplement;
    QLabel* textLabelCodePostal;
    QLabel* labelEtatCivilTelephone;
    QLabel* labelEtatCivilTelephone_2;
    QLabel* textLabel2;
    QComboBox* comboBoxEtatCivilCivilite;
    QLabel* labelEtatCivilNom;
    QLineEdit* lineEditEtatCivilNom;
    QLabel* textLabel3_2;
    QLineEdit* lineEditEtatCivilNomJeuneFille;
    QLabel* labelEtatCivilPrenom;
    QLineEdit* lineEditEtatCivilPrenom;
    QLabel* labelEtatCivilDateNaissance;
    QDateEdit* dateEditEtatCivilDateNaissance;
    QLabel* textLabel1_4;
    QLineEdit* lineEditEtatCivilLieuNaissance;
    QLabel* labelEtatCivilRue;
    QLabel* textLabelEtatCivilVille;
    QComboBox* comboBoxBenefProspect;
    QLineEdit* lineEditEtatCivilEmail;
    QLabel* labelEtatCivilEmail;
    QLabel* labelEtatCivilRaisonSociale;
    QComboBox* comboBoxEtatCivilRaisonSociale;
    QLineEdit* lineEditEtatCivilRue;
    QLineEdit* lineEditEtatCivilAdresseComplement;
    QLineEdit* lineEditEtatCivilVille;
    QLineEdit* lineEditEtatCivilTelephonePortable;
    QLineEdit* lineEditEtatCivilTelephone;
    QLineEdit* lineEditEtatCivilCodePostal;
    QLineEdit* lineEditEtatCivilAdresseComplementGestion;
    QLineEdit* lineEditEtatCivilCodePostalGestion;
    QLineEdit* lineEditEtatCivilVilleGestion;
    QLineEdit* lineEditEtatCivilTelephonePro;
    QLineEdit* lineEditEtatCivilTelephoneFax;
    QLabel* textLabelEtatCivilRue_2;
    QLabel* textLabelEtatCivilAdresseComplement_2;
    QLabel* labelEtatCivilTelephone_3;
    QLabel* textLabelCodePostal_2;
    QLabel* labelEtatCivilTelephone_3_2;
    QLabel* textLabelEtatCivilVille_2;
    QLabel* labelEtatCivilRue_2;
    QLineEdit* lineEditEtatCivilRueGestion;
    QLabel* labelEtatCivilSituationFamilliale;
    QComboBox* comboBoxEtatCivilSituationFamilliale;
    QLabel* labelEtatCivilConseils;
    QFrame* frameEtatCivilConseils;
    QComboBox* comboBoxEtatCivilCabinetComptable;
    QComboBox* comboBoxEtatCivilExpertComptable;
    QLabel* labelEtatCivilExpertComptable_3;
    QLabel* labelEtatCivilNotaire_3;
    QLabel* labelEtatCivilAvocat_3;
    QLabel* labelEtatCivilCabinetComptable_3;
    QLabel* labelEtatCivilEtude_3;
    QLabel* labelEtatCivilCabinetAvocat_3;
    QComboBox* comboBoxEtatCivilEtude;
    QComboBox* comboBoxEtatCivilCabinetAvocat;
    QComboBox* comboBoxEtatCivilNotaire;
    QComboBox* comboBoxEtatCivilAvocat;
    QWidget* WStackPage_3;
    QTabWidget* tabWidgetFamille;
    QWidget* tab;
    QFrame* frameConjoint;
    QLabel* labelFamilleNom;
    QLabel* labelFamilleAdresse;
    QLabel* labelFamilleDateNaissance;
    QLabel* textLabelFamilleRue;
    QLabel* textLabelFamilleAdresseComplement;
    QLabel* textLabelFamilleCodePostal;
    QLineEdit* lineEditFamilleCodePostal;
    QLabel* textLabelFamilleVille;
    QLineEdit* lineEditFamilleVille;
    QComboBox* comboBoxFamilleConjoint;
    QLabel* textLabel4;
    QDateEdit* dateEditFamilleDateNaissance;
    QLineEdit* lineEditFamilleNomRue;
    QLabel* labelFamilleTelephone;
    QLineEdit* lineEditFamilleTelephone;
    QLabel* labelFamilleTelephone_2;
    QLineEdit* lineEditFamilleEmail;
    QLabel* labelFamilleEmail;
    QLabel* labelFamilleTelephone_3;
    QLabel* labelFamilleTelephone_2_2;
    QLineEdit* lineEditFamilleLieuNaissance;
    QLineEdit* lineEditFamilleTelephonePro;
    QLineEdit* lineEditFamilleTelephonePortable;
    QLineEdit* lineEditFamilleTelephoneFax;
    QLineEdit* lineEditFamilleAdresseComplement;
    QFrame* frame8;
    QLabel* labelFamilleSalaireAnnuel;
    QLabel* labelFamilleBNC;
    QLabel* labelFamilleBIC;
    QLabel* labelFamilleRevenusFonciers;
    QLabel* labelFamilleDividendes;
    QLabel* labelFamilleAutresRevenus;
    QComboBox* comboBoxFamilleNetBrut;
    QLineEdit* lineEditFamilleAutresRevenus;
    QLineEdit* lineEditFamilleDividendes;
    QLineEdit* lineEditFamilleBNC;
    QLineEdit* lineEditFamilleBIC;
    QLineEdit* lineEditFamilleSalaireAnnuel;
    QLineEdit* lineEditFamilleRevenusFonciers;
    QWidget* tab_2;
    QLabel* labelFamilleDateMariage;
    QDateEdit* dateEditFamilleDateMariage;
    QLabel* textLabel5;
    QLineEdit* lineEditFamilleRgMariage;
    QLabel* labelFamilleRegimeMatrimonial;
    QComboBox* comboBoxFamilleRegimeMatrimonial;
    QCheckBox* checkBoxFamilleDonationDernierVivant;
    QLabel* textLabel2_4;
    QTextEdit* textEditFamilleAutreDispo;
    QLabel* labelFamilleDureeMariages;
    QLabel* labelFamilleMonsieur;
    QLineEdit* lineEditFamilleDureeMariagesPrecedentsMonsieur;
    QLabel* labelFamilleMadame;
    QLineEdit* lineEditFamilleDureeMariagesPrecedentsMadame;
    QLabel* labelFamilleNombreEnfants;
    QLineEdit* lineEditFamilleNombreEnfantsCommuns;
    QLabel* labelFamilleNombreEnfantsMonsieur;
    QLineEdit* lineEditFamilleNombreEnfantsMonsieur;
    QLabel* labelFamilleNombreEnfantsMadame;
    QLineEdit* lineEditFamilleNombreEnfantsMadame;
    QLabel* textLabel3;
    QPushButton* pushButtonEnfantPlus;
    QPushButton* pushButtonEnfantsMinus;
    QListView* listViewEnfants;
    QLabel* labelFamilleDispositionsTestamentaires;
    QLabel* labelFamilleDonationEntreEpoux;
    QLineEdit* lineEditFamilleDispositionsTestamentaires;
    QLineEdit* lineEditFamilleDonationEntreEpoux;
    QWidget* WStackPage_4;
    QLabel* labelCarriereRevenus;
    QFrame* frame8_2;
    QLabel* labelCarriereSalaireAnnuel;
    QLabel* labelCarriereBNC;
    QLabel* labelCarriereBIC;
    QLabel* labelCarriereRevenusFonciers;
    QLabel* labelCarriereDividendes;
    QLabel* labelCarriereAutresRevenus;
    QComboBox* comboBoxCarriereNetBrut;
    QLineEdit* lineEditCarriereAutresRevenus;
    QLineEdit* lineEditCarriereDividendes;
    QLineEdit* lineEditCarriereBNC;
    QLineEdit* lineEditCarriereBIC;
    QLineEdit* lineEditCarriereSalaireAnnuel;
    QLineEdit* lineEditCarriereRevenusFonciers;
    QLineEdit* lineEditRevenusEmployeur;
    QLabel* textLabel3_3;
    QLabel* textLabel5_3;
    QFrame* frame10;
    QLabel* labelCarriereMontantImpot;
    QLabel* labelCarriereMontantImpotMonsieur;
    QLineEdit* lineEditCarriereMontantImpotMonsieur;
    QLabel* labelCarriereMontantImpotMadame;
    QLineEdit* lineEditCarriereMontantImpotMadame;
    QLabel* labelCarriereISF;
    QComboBox* comboBoxCarriereISF;
    QLabel* labelCarriereMontant;
    QLineEdit* lineEditCarriereMontantISF;
    QLabel* labelCarriereCGA;
    QComboBox* comboBoxCarriereCGA;
    QLabel* labelCarriereDeductions;
    QLabel* labelCarriereDeductionsMonsieur;
    QLineEdit* lineEditCarriereDeductionsMonsieur;
    QLabel* labelCarriereDeductionMadame;
    QLineEdit* lineEditCarriereDeductionsMadame;
    QComboBox* comboBoxRevenusMoisBilan;
    QComboBox* comboBoxStatutPro;
    QLabel* textLabel4_3;
    QLabel* labelCarriereFiscalite;
    QLabel* textLabel6;
    QLineEdit* lineEditRevenusFonction;
    QLabel* labelCarriereEmplois;
    QPushButton* pushButtonCarriereEmploiPlus;
    QPushButton* pushButtonCarriereEmploiMinus;
    QListView* listViewCarriereEmploi;
    QLabel* labelCarriereAgeRetraite;
    QLineEdit* lineEditCarriereAgeRetraite;
    QWidget* WStackPage_5;
    QTabWidget* tabWidget3;
    QWidget* tab_3;
    QComboBox* comboBoxPrevoyanceSanteSource;
    QCheckBox* checkBoxPrevoyanceSanteCaractereViagerEntreprise;
    QLineEdit* lineEditPrevoyanceSanteNiveauGarantie;
    QLabel* labelPrevoyanceSanteCompagnie;
    QLabel* labelPrevoyanceCotisationAnnuelle;
    QLabel* labelPrevoyanceNiveauGarantie;
    QLabel* textLabel1_5;
    QCheckBox* checkBoxPrevoyanceSanteCaractereViagerNon;
    QCheckBox* checkBoxPrevoyanceSanteCaractereViagerOui;
    QLabel* labelPrevoyanceSanteFiscalite;
    QLabel* labelPrevoyanceSanteCaractereViager;
    QLabel* labelPrevoyanceSanteDateEffet;
    QDateEdit* dateEditPrevoyanceDateEffet;
    QLineEdit* lineEditPrevoyanceSanteFiscalite;
    QLineEdit* lineEditPrevoyanceSanteCotisationAnnuelle;
    QLineEdit* lineEditPrevoyanceSanteContrat;
    QLabel* labelPrevoyanceIndiceSatisfaction;
    QLabel* labelPrevoyanceBeneficiaires;
    QLineEdit* lineEditPrevoyanceSanteIndiceSatisfaction;
    QLabel* labelPrevoyanceSanteContrat;
    QCheckBox* checkBoxPrevoyanceSanteCaractereViagerPersonnel;
    QComboBox* comboBoxPrevoyanceSanteBeneficiaires;
    QTextEdit* textEditNotesPrevoyanceSante;
    QLabel* textLabel1_6;
    QComboBox* comboBoxPrevoyanceSanteCompagnie;
    QWidget* TabPage;
    QLabel* textLabel34;
    QFrame* frame13;
    QLabel* labelPrevoyanceSanteCapitauxInvalidite;
    QLineEdit* lineEditPrevoyanceSanteCapitauxInvalidite;
    QLabel* labelPrevoyanceSanteInvalidite33;
    QLabel* labelPrevoyanceSanteInvaliditeMiseAJour;
    QLabel* labelPrevoyanceSanteInvalidite66;
    QLabel* labelPrevoyanceSanteMontantRente;
    QLabel* labelPrevoyanceSanteInvalidite100;
    QDateEdit* dateEditPrevoyanceSanteInvaliditeDateEffet;
    QLabel* labelPrevoyanceSanteInvaliditeProfessionnelle;
    QLineEdit* lineEditPrevoyanceSanteInvalidite100;
    QLineEdit* lineEditPrevoyanceSanteInvalidite33;
    QDateEdit* dateEditPRevoyanceSanteInvaliditeMiseAJour;
    QComboBox* comboBoxPrevoyanceSanteInvaliditeProfessionnelle;
    QLabel* labelPrevoyanceSanteInvaliditeDateEffet;
    QLineEdit* lineEditPrevoyanceSanteInvalidite66;
    QComboBox* comboBoxPrevoyanceSanteInvaliditeFiscalite;
    QLabel* labelPrevoyanceSanteInvaliditeCompagnie;
    QComboBox* comboBoxPrevoyanceSanteInvaliditeCompagnie;
    QLabel* labelPrevoyanceSanteInvaliditeFiscalite;
    QTextEdit* textEditNotesPrevoyanceInvalidite;
    QLabel* textLabel2_5;
    QFrame* frameArretDeTravail;
    QLabel* labelPrevoyanceSanteArretTravailAccordAssocies;
    QLabel* labelPrevoyanceSanteArretTravailDateEffet;
    QDateEdit* dateEditPrevoyanceSanteArretTravailDateEffet;
    QLabel* labelPrevoyanceSanteArretTravailDuree;
    QComboBox* comboBoxPrevoyanceSanteArretTravailAccordAssocies;
    QLabel* labelPrevoyanceSanteArretTravailDateMiseAJour;
    QLineEdit* lineEditPrevoyanceSanteArretTravailDuree;
    QDateEdit* dateEditPrevoyanceSanteArretTravailDateMiseAJour;
    QPushButton* pushButtonPrevoyanceArretTravailMinus;
    QPushButton* pushButtonPrevoyanceArretTravailPlus;
    QListView* listViewArretTravail;
    QLabel* labelPrevoyanceSanteContratArretTravail;
    QLabel* labelPrevoyanceSanteFranchises;
    QLineEdit* lineEditPrevoyanceSanteHospitalisation;
    QLineEdit* lineEditPrevoyanceSanteMaladie;
    QLabel* labelPrevoyanceSanteCompagnieArretTravail;
    QLabel* labelPrevoyanceanteHospitalisation;
    QLabel* labelPrevoyanceSanteFiscaliteArretTravail;
    QLabel* labelPrevoyanceAccident;
    QLabel* labelPrevoyanceSanteMaladie;
    QLineEdit* lineEditPrevoyanceSanteContratArretTravail;
    QLineEdit* lineEditPrevoyanceSanteAccident;
    QComboBox* comboBoxPrevoyanceSanteFiscaliteArretTravail;
    QComboBox* comboBoxPrevoyanceSanteCompagnieArretTravail;
    QLabel* labelPrevoyanceArretTravail;
    QWidget* TabPage_2;
    QLabel* textLabelPrevoyanceDecesGarantie;
    QPushButton* pushButtonPrevoyanceGarantieDecesPlus;
    QPushButton* pushButtonPrevoyanceGarantieDecesMinus;
    QListView* listViewGarantieDeces;
    QLabel* labelPrevoyanceDecesRenteConjoint_2;
    QLabel* textLabel1_7;
    QTextEdit* textEditPrevoyanceDecesNotes;
    QLabel* labelPrevoyanceDecesRenteConjointCompagnie;
    QDateEdit* dateEditPrevoyanceDecesRenteConjointDateEffet;
    QLabel* labelPeevoyanceDecesRenteFiscalite;
    QLabel* labelPrevoyanceDecesRenteConjointDateEffet;
    QComboBox* comboBoxPrevoyanceDecesRenteConjointFiscalite;
    QLabel* labelPeevoyanceDecesRenteMontant;
    QLineEdit* lineEditPrevoyanceDecesRenteConjointMontant;
    QLineEdit* lineEditPrevoyanceRenteConjointDuree;
    QComboBox* comboBoxPrevoyanceDecesCompagnieConjoint;
    QLabel* labelPeevoyanceDecesRenteDuree;
    QDateEdit* dateEditPrevoyanceDecesRenteEducationDateEffet;
    QLabel* labelPrevoyanceDecesRenteEducationDateEffet;
    QPushButton* pushButtonPrevoyanceRenteEducationPlus;
    QPushButton* pushButtonPrevoyanceRenteEducationMinus;
    QLabel* labelPrevoyanceDecesRenteEducationFiscalite;
    QLabel* labelPrevoyanceDecesRenteEducationCompagnie;
    QListView* listViewRenteEducation;
    QComboBox* comboBoxPrevoyanceDecesRenteEducationFiscalite;
    QComboBox* comboBoxPrevoyanceDecesRenteEducationCompagnie;
    QLabel* labelPrevoyanceDecesRenteConjoint;
    QWidget* tab_4;
    QLabel* labelPrevoyanceSanteFraixGeneraux;
    QFrame* frame11;
    QLabel* labelPrevoyanceSanteCouvertureMensuelle;
    QLabel* labelPrevoyanceSanteCompagnieFraisGeneraux;
    QLineEdit* lineEditPrevoyanceSanteCouvertureMensuelle;
    QLineEdit* lineEditPrevoyanceSanteFranchise;
    QDateEdit* dateEditPrevoyanceSanteDureeFraisGeneraux;
    QLabel* labelPrevoyanceSanteFranchise;
    QLineEdit* lineEditPrevoyanceSanteContratFraisGeneraux;
    QLabel* labelPrevoyanceSanteContratFraisGeneraux;
    QLabel* labelPrevoyanceSanteDureeFraisGeneraux;
    QComboBox* comboBoxPrevoyanceSanteCompagnieFraisGeneraux;
    QLabel* textLabel31;
    QPushButton* pushButtonPrevoyanceEmpruntPlus;
    QPushButton* pushButtonPrevoyanceEmpruntMinus;
    QListView* listViewEmprunt;
    QLabel* textLabel1_8;
    QTextEdit* textEditPrevoyanceElpruntNotes;
    QWidget* WStackPage_6;
    QTabWidget* tabWidgetEpargne;
    QWidget* tab_5;
    QLabel* textLabelEpargne;
    QPushButton* pushButtonEpargneCapitalisationPlus;
    QPushButton* pushButtonEpargneCapitalisationMinus;
    QListView* listViewEpargne;
    QLabel* textLabelEpargne_2;
    QPushButton* pushButtonEpargneAssurancePlus;
    QPushButton* pushButtonEpargneAssuranceMinus;
    QListView* listViewAssuranceVie;
    QLabel* textLabel14;
    QLabel* textLabel13;
    QLabel* textLabel12;
    QLabel* textLabelSensibilie;
    QSlider* sliderEpargneSensibilite;
    QLabel* textLabel15;
    QComboBox* comboBoxMotivation;
    QComboBox* comboBoxMotivation_2;
    QComboBox* comboBoxMotivation_3;
    QComboBox* comboBoxMotivation_4;
    QWidget* tab_6;
    QLabel* textLabelEpargne_2_2;
    QPushButton* pushButtonEpargneComptePlus;
    QPushButton* pushButtonEpargneCompteMinus;
    QListView* listViewComptes;
    QLabel* textLabelEpargne_2_2_2;
    QPushButton* pushButtonEpargneRevenusPlus;
    QPushButton* pushButtonEpargneRevenusMinus;
    QListView* listViewRevenus;
    QLabel* textLabelEpargne_2_2_2_2;
    QPushButton* pushButtonEpargneChargesPlus;
    QPushButton* pushButtonEpargneChargesMinus;
    QListView* listViewCharges;
    QLabel* textLabel17_2;
    QLabel* textLabel17;
    QLabel* textLabel17_2_2;
    QWidget* WStackPage_7;
    QLabel* textLabel18;
    QWidget* WStackPage_8;
    QLabel* textLabel7;
    QLineEdit* lineEditBesoinPrevoyance;
    QLineEdit* lineEditBesoinPatrimoine;
    QLabel* textLabel8;
    QLabel* textLabel12_2;
    QLineEdit* lineEditBesoinsRetraite;
    QLabel* textLabel11;
    QLineEdit* lineEditBesoinSante;
    QLabel* textLabel10;
    QLabel* textLabel9;
    QLineEdit* lineEditBesoinEpargne;
    QLabel* textLabel13_2;
    QTextEdit* textEditBesoinNotes;
    QWidget* WStackPage_9;
    QFrame* frameRechercher;
    QLabel* textLabelListerFiltreNom;
    QLineEdit* lineEditListerFiltreNom;
    QComboBox* comboBoxSearchProspect;
    QLineEdit* lineEditListerFiltrePrenom;
    QLabel* textLabelListerFiltrePrenom;
    QPushButton* pushButtonPersonneFiltreEffacer;
    QComboBox* comboBoxSearchFunction;
    QComboBox* comboBoxSearchOp1;
    QLabel* textLabelSearch1;
    QLineEdit* lineEditSearchValue1;
    QLineEdit* lineEditSearchValue2;
    QLabel* textLabelSearch2;
    QComboBox* comboBoxSearchOp2;
    QListView* listView;
    QWidget* WStackPage_10;
    QPushButton* pushButtonDossierEntreprise;
    QPushButton* pushButtonParticipants;
    QPushButton* pushButtonTNS;
    QWidgetStack* widgetStackEntreprise;
    QWidget* WStackPage_11;
    QTabWidget* tabWidgetEntreprise;
    QWidget* tab_7;
    QLabel* textLabel1_2;
    QLineEdit* lineEditRaisonSociale;
    QLabel* textLabel6_2;
    QLineEdit* lineEditCodeNaf;
    QLabel* textLabel7_2;
    QLineEdit* lineEditNumSiret;
    QLabel* textLabel8_2;
    QLineEdit* lineEditActivite;
    QLabel* textLabel9_2;
    QLineEdit* lineEditConventionCollective;
    QLabel* textLabel15_2_2;
    QLabel* textLabel12_2_2;
    QLineEdit* lineEditColGer;
    QLabel* textLabel13_2_2;
    QLineEdit* lineEditProche;
    QLabel* textLabel14_2_2;
    QLineEdit* lineEditAutre;
    QLabel* textLabel16_2;
    QLabel* textLabel17_3_3;
    QLineEdit* lineEditBenefN1;
    QLabel* textLabel17_3_2_2;
    QLineEdit* lineEditBenefN2;
    QLabel* textLabel18_2_2;
    QComboBox* comboBoxRegimeFiscal;
    QLabel* textLabel2_2;
    QComboBox* comboBoxFormeJuridique;
    QLabel* textLabel3_2_2;
    QLineEdit* lineEditAutreFormeJuridique;
    QLabel* textLabel1_9;
    QLineEdit* lineEditDateCreation;
    QComboBox* comboBoxSuiteEco;
    QLabel* textLabel2_6;
    QCheckBox* checkBoxAGA;
    QCheckBox* checkBoxCGA;
    QLabel* textLabelEtatCivilRue_2_2;
    QLineEdit* lineEditEntrepriseComplement;
    QLabel* textLabelEtatCivilAdresseComplement_2_2;
    QLabel* textLabel5_2;
    QLabel* textLabel4_2;
    QLineEdit* lineEditEntrepriseNomRue;
    QLabel* textLabelCodePostal_2_2;
    QLineEdit* lineEditEntrepriseCodePostal;
    QLineEdit* lineEditEntrepriseVille;
    QLineEdit* lineEditTelEnses;
    QLabel* textLabel3_4;
    QLineEdit* lineEditFaxEntses;
    QLabel* textLabel3_4_2;
    QLineEdit* lineEdithttpentses;
    QLabel* textLabel20_2;
    QLineEdit* lineEditNomGerant;
    QLabel* textLabel7_3;
    QLineEdit* lineEditPrenomGerant;
    QLabel* textLabel8_3;
    QDateEdit* dateEditNaissanceGerant;
    QComboBox* comboBoxPartsDirigeant;
    QPushButton* pushButtonDirigeantPlus;
    QPushButton* pushButtontDirigeantMinus;
    QListView* listViewDirigeants;
    QLabel* textLabel19_2;
    QWidget* TabPage_3;
    QLineEdit* lineEditNbCadres;
    QLineEdit* lineEditNbNonCadres;
    QLabel* textLabel22_2_2;
    QLineEdit* lineEditNbAutreColleges;
    QLineEdit* lineEditNbETAM;
    QLabel* textLabel22_4_2;
    QLabel* textLabel22_5;
    QLabel* textLabel22_3_2;
    QLabel* textLabel23_3_2;
    QComboBox* comboBoxDeleguePersonnel;
    QLabel* textLabel23_4;
    QLineEdit* lineEditInteressementMod;
    QComboBox* comboBoxInteressement;
    QComboBox* comboBoxComiteEntreprise;
    QLabel* textLabel23_2_2;
    QLabel* textLabel25_2;
    QLineEdit* lineEditARRCOPP;
    QLineEdit* lineEditARRCOPS;
    QLabel* textLabel26_2;
    QLabel* textLabel29_2_2;
    QLineEdit* lineEditAGIRCPP;
    QLabel* textLabel27_2;
    QLineEdit* lineEditAutrePS;
    QLabel* textLabel29_3;
    QLineEdit* lineEditAGIRCPS;
    QLabel* textLabel28_2;
    QLineEdit* lineEditAutrePP;
    QLabel* textLabel30_2_2;
    QLineEdit* lineEditCaisseCongesPayes;
    QLabel* textLabel30_3_2;
    QLineEdit* lineEditTauxAccidentTravail;
    QLabel* textLabel30_4;
    QLineEdit* lineEditTaxeTransport;
    QWidget* TabPage_4;
    QLabel* textLabel31_2_2;
    QPushButton* pushButtonEntrepriseRetraitePlus;
    QPushButton* pushButtonEntrepriseRetraiteMinus;
    QLabel* textLabel32_2;
    QListView* listViewEntrepriseRetraite;
    QLabel* textLabel33_2;
    QLineEdit* lineEditOrganisme;
    QLabel* textLabel34_2_2;
    QDateEdit* dateEditEntreprisePEE;
    QLabel* textLabel35_2;
    QComboBox* comboBoxEntrepriseInteressement;
    QLabel* textLabel36_3;
    QLineEdit* lineEditRetraiteInteressementN1;
    QLabel* textLabel36_2_2;
    QLineEdit* lineEditRetraiteInteressementN2;
    QWidget* TabPage_5;
    QLabel* textLabel2_7;
    QLabel* textLabel3_5;
    QLabel* textLabel4_4;
    QListView* listViewPrevoyanceEntses;
    QListView* listViewPrevoyance2Entses;
    QPushButton* pushButtonPrevoyanceEntsesMinus;
    QPushButton* pushButtonPrevoyanceEntsesPlus;
    QLabel* textLabel5_4;
    QLabel* textLabel6_3;
    QPushButton* pushButtonPrevoyance2EntsesMinus;
    QPushButton* pushButtonPrevoyance2EntsesPlus;
    QLabel* textLabel1_10;
    QWidget* WStackPage_12;
    QLabel* textLabel1_11;
    QLineEdit* lineEditEntsesNomEmploye;
    QLabel* textLabel2_8;
    QLineEdit* lineEditEntsesPrenomEmploye;
    QLabel* textLabel3_6;
    QDateEdit* dateEditEntsesNaissanceEmploye;
    QPushButton* pushButtonEnstesEmployePlus;
    QPushButton* pushButtonEnstesEmployeMinus;
    QLabel* textLabel1_3;
    QListView* listViewEntsesParticipants;
    QWidget* WStackPage_13;
    QLabel* textLabel2_3;
    QListView* listView29;
    QWidget* WStackPage_14;
    QFrame* frameRechercher_2;
    QLabel* textLabelListerFiltreNom_2;
    QLineEdit* lineEditListerFiltreRaisonSociale;
    QLabel* textLabelListerFiltrePrenom_2;
    QLineEdit* lineEditListerFiltreSiret;
    QPushButton* pushButtonListerFiltrerPlus_2;
    QPushButton* pushButtonEntsesFiltreEffacer;
    QListView* listViewEntses;
    QMenuBar *MenuBar;
    QPopupMenu *Fichier;
    QPopupMenu *Edition;
    QPopupMenu *Outils;
    QPopupMenu *Aide;
    QAction* filenew_itemOuvrir;
    QAction* filenew_itemSauvegarder;
    QAction* filenew_itemQuitter;
    QAction* filenew_itemSauvegarderSous;
    QAction* help_itemAbout;
    QAction* outils__itemPreferences;
    QAction* menuChargerAction;
    QAction* fichierImporterAction;
    QAction* filenew_itemSauvegarderSousnew_itemAction;
    QAction* fichierExporterAction;

    QListView * getListViewPersonnes();
    QListView * getListViewEntses();

public slots:
    virtual void ajouter();
    virtual void lister();
    virtual void pushButtonAjouterEntreprise_clicked();
    virtual void pushButtonEntrepriseLister_clicked();
    virtual void ouvrir();
    virtual void filenew_itemSauvegarder_activated();
    virtual void sauvegarder();
    virtual void about();
    virtual void preferences();
    virtual void widgetStackAjouter_EtatCivil();
    virtual void widgetStackAjouter_Famille();
    virtual void widgetStackAjouter_Carriere();
    virtual void widgetStackAjouter_Prevoyance();
    virtual void widgetStackAjouter_Epargne();
    virtual void widgetStackAjouter_Patrimoine();
    virtual void pushButtonBesoins_clicked();
    virtual void pushButtonDossierEntreprise_clicked();
    virtual void pushButtonParticipants_clicked();
    virtual void pushButtonTNS_clicked();
    virtual void toolButtonSupprimer_clicked();
    virtual void charger();
    virtual void comboBoxInteressement_activated( int iVal );
    virtual void chargerPersonne( QListViewItem * item );
    virtual void comboBoxFamilleConjoint_textChanged( const QString & str );
    virtual void sliderEpargneSensibilite_valueChanged( int i );
    virtual void listViewProspect_doubleClicked( QListViewItem * item );
    virtual void comboBoxEtatCivilCabinetComptable_textChanged( const QString & str );
    virtual void comboBoxEtatCivilEtude_textChanged( const QString & str );
    virtual void comboBoxEtatCivilCabinetAvocat_textChanged( const QString & str );
    virtual void comboBoxBenefProspect_activated( int i );
    virtual void pushButtonDirigeantPlus_clicked();
    virtual void pushButtontDirigeantMinus_clicked();
    virtual void comboBoxEtatCivilRaisonSociale_activated( int i );
    virtual void pushButtonEnstesEmployeMinus_clicked();
    virtual void pushButtonEnstesEmployePlus_clicked();
    virtual void listView29_doubleClicked( QListViewItem * item );
    virtual void listViewEntsesParticipants_doubleClicked( QListViewItem * item );
    virtual void listViewDirigeants_doubleClicked( QListViewItem * item );
    virtual void fichierImporterAction_activated();
    virtual void lineEditListerFiltreNom_textChanged( const QString & str );
    virtual void lineEditListerFiltrePrenom_textChanged( const QString & str );
    virtual void comboBoxSearchProspect_activated( int uId );
    virtual void lineEditListerFiltreSiret_textChanged( const QString & str );
    virtual void lineEditListerFiltreRaisonSociale_textChanged( const QString & str );
    virtual void pushButtonEntsesFiltreEffacer_clicked();
    virtual void pushButtonPersonneFiltreEffacer_clicked();
    virtual void lineEditSearchValue1_textChanged( const QString & str );
    virtual void lineEditSearchValue2_textChanged( const QString & str );
    virtual void comboBoxSearchFunction_activated( int i );
    virtual void comboBoxSearchOp1_highlighted();
    virtual void comboBoxSearchOp2_highlighted();
    virtual void fichierExporterAction_activated();

protected:
    QVBoxLayout* dlgMainLayout;
    QHBoxLayout* layout182;
    QSpacerItem* spacer118;
    QHBoxLayout* WStackPageLayout;
    QVBoxLayout* layout70;
    QVBoxLayout* WStackPageLayout_2;
    QGridLayout* frameBeneficiaireLayout;
    QSpacerItem* spacer36;
    QSpacerItem* spacer118_2;
    QHBoxLayout* layout68;
    QHBoxLayout* layout69;
    QHBoxLayout* layout65;
    QGridLayout* frameEtatCivilConseilsLayout;
    QSpacerItem* spacer2_3;
    QSpacerItem* spacer3_3;
    QSpacerItem* spacer4_3;
    QVBoxLayout* WStackPageLayout_3;
    QGridLayout* tabLayout;
    QSpacerItem* spacer32;
    QSpacerItem* spacer33_2;
    QGridLayout* frameConjointLayout;
    QSpacerItem* spacer1_2_2;
    QVBoxLayout* frame8Layout;
    QHBoxLayout* layout15;
    QVBoxLayout* layout14;
    QGridLayout* layout13;
    QSpacerItem* spacer18;
    QVBoxLayout* tabLayout_2;
    QHBoxLayout* layout66;
    QHBoxLayout* layout67;
    QHBoxLayout* layout68_2;
    QHBoxLayout* layout9;
    QHBoxLayout* layout8;
    QHBoxLayout* layout376;
    QHBoxLayout* layout17;
    QVBoxLayout* layout6;
    QVBoxLayout* layout16;
    QGridLayout* WStackPageLayout_4;
    QSpacerItem* spacer33;
    QVBoxLayout* frame8_2Layout;
    QHBoxLayout* layout15_2;
    QVBoxLayout* layout14_2;
    QGridLayout* layout13_2;
    QSpacerItem* spacer18_2;
    QGridLayout* layout61;
    QSpacerItem* spacer27;
    QVBoxLayout* frame10Layout;
    QHBoxLayout* layout21;
    QHBoxLayout* layout26;
    QHBoxLayout* layout21_2;
    QHBoxLayout* layout223;
    QHBoxLayout* layout65_2;
    QSpacerItem* spacer39;
    QHBoxLayout* WStackPageLayout_5;
    QGridLayout* tabLayout_3;
    QSpacerItem* spacer30;
    QGridLayout* TabPageLayout;
    QGridLayout* frame13Layout;
    QHBoxLayout* layout30;
    QGridLayout* frameArretDeTravailLayout;
    QSpacerItem* spacer12_2;
    QSpacerItem* spacer8;
    QGridLayout* layout28_2;
    QGridLayout* TabPageLayout_2;
    QSpacerItem* spacer40;
    QHBoxLayout* layout101;
    QHBoxLayout* layout69_2;
    QVBoxLayout* layout49;
    QVBoxLayout* tabLayout_4;
    QGridLayout* frame11Layout;
    QSpacerItem* spacer9;
    QHBoxLayout* layout50;
    QHBoxLayout* layout71;
    QVBoxLayout* WStackPageLayout_6;
    QGridLayout* tabLayout_5;
    QSpacerItem* spacer14;
    QSpacerItem* spacer13;
    QHBoxLayout* layout35;
    QHBoxLayout* layout35_2;
    QVBoxLayout* tabLayout_6;
    QHBoxLayout* layout35_2_2;
    QHBoxLayout* layout35_2_2_2;
    QHBoxLayout* layout35_2_2_2_2;
    QVBoxLayout* WStackPageLayout_7;
    QSpacerItem* spacer29;
    QGridLayout* layout72;
    QSpacerItem* spacer28_2;
    QVBoxLayout* WStackPageLayout_8;
    QGridLayout* frameRechercherLayout;
    QSpacerItem* spacer41;
    QSpacerItem* spacer40_2;
    QHBoxLayout* WStackPageLayout_9;
    QVBoxLayout* layout168;
    QSpacerItem* spacer47;
    QGridLayout* WStackPageLayout_10;
    QGridLayout* tabLayout_7;
    QSpacerItem* spacer133;
    QHBoxLayout* layout45_2;
    QHBoxLayout* layout48_2;
    QHBoxLayout* layout50_3;
    QHBoxLayout* layout52_2;
    QHBoxLayout* layout65_2_2;
    QHBoxLayout* layout53_2;
    QHBoxLayout* layout66_2;
    QHBoxLayout* layout44_2;
    QGridLayout* layout47_2;
    QSpacerItem* spacer15_2;
    QHBoxLayout* layout60;
    QVBoxLayout* TabPageLayout_3;
    QSpacerItem* spacer19_2;
    QGridLayout* layout71_2;
    QGridLayout* layout67_2;
    QGridLayout* layout68_2_2;
    QGridLayout* layout73_2;
    QSpacerItem* spacer18_3_2;
    QGridLayout* layout74_2;
    QGridLayout* TabPageLayout_4;
    QSpacerItem* spacer35;
    QHBoxLayout* layout75_2;
    QHBoxLayout* layout76_2;
    QSpacerItem* spacer22_2;
    QHBoxLayout* layout77_2;
    QHBoxLayout* layout90_2;
    QGridLayout* TabPageLayout_5;
    QSpacerItem* spacer37;
    QSpacerItem* spacer36_2;
    QSpacerItem* spacer38;
    QSpacerItem* spacer39_2;
    QSpacerItem* spacer36_2_2;
    QVBoxLayout* WStackPageLayout_11;
    QHBoxLayout* layout60_2;
    QVBoxLayout* WStackPageLayout_12;
    QVBoxLayout* WStackPageLayout_13;
    QGridLayout* frameRechercher_2Layout;
    QSpacerItem* spacer79;
    QSpacerItem* spacer12_3;

protected slots:
    virtual void languageChange();

private:
    virtual void AjouterValider();
    virtual void supprimer();
    virtual void ValiderAjoutEntses();
    void chargerEntreprise();
    virtual void resetEntses();
    virtual void resetPersonne();

};

#endif // DLGMAIN_H
